package br.com.feliperudolfe.comum.configuracao;

public enum MsgRef {

	CMP_TAM_MIN,
	CMP_TAM_MAX,
	CMP_INVA,
	CMP_INVO,
	CMP_OBG,
	CMP_OBGA,

	REQ_INV,
	REQ_INT,
	REQ_ERRO,
	MSG_SERVICO_PROTEGIDO,
	MSG_USUARIO_NAO_AUTORIZADO,
	MSG_USUARIO_INEXISTENTE_INVALIDO,

	MSG_CADASTRADO_COM_SUCESSO,
	MSG_NAO_FOI_POSSIVEL_CLONAR_ENTIDADE,
	MSG_NAO_FOI_POSSIVEL_CONVERTER_ENTIDADE,
	MSG_NAO_ENCONTRADO,
	MSG_NAO_ENCONTRADA,
	MSG_JA_CADASTRADO,
	MSG_JA_CADASTRADA

}